apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - mongo-ca-secret.yaml
  - mongo-client-secret.yaml
components:
  - ../../components/servicemonitor
  - ../../components/grafana-dashboard
  - ../../components/tracing
patches:
  - path: configmap-patch.yaml
  - path: secret-patch.yaml
  - path: httproute-patch.yaml
  - path: deployment-patch.yaml
images:
  - name: ghcr.io/prafdin/simple-workflows
    newTag: latest
