apiVersion: v1
kind: Secret
metadata:
  name: simple-workflows-mongo-client-cert
type: Opaque
stringData:
  tls.crt: |
    REPLACE_WITH_YOUR_MONGODB_CLIENT_CERTIFICATE_PEM
  tls.key: |
    REPLACE_WITH_YOUR_MONGODB_CLIENT_PRIVATE_KEY_PEM
