apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-workflows
spec:
  template:
    spec:
      containers:
        - name: simple-workflows
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(HOST_IP):4317
            - name: OTEL_SERVICE_NAME
              value: simple-workflows
