apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-workflows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-workflows
  template:
    metadata:
      labels:
        app: simple-workflows
    spec:
      serviceAccountName: simple-workflows
      containers:
        - name: simple-workflows
          image: simple-workflows:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: simple-workflows-config
            - secretRef:
                name: simple-workflows-mongo-credentials
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
