apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/servicemonitor
patches:
  - path: configmap-patch.yaml
  - path: secret-patch.yaml
  - path: httproute-patch.yaml
images:
  - name: ghcr.io/prafdin/simple-workflows
    newTag: latest
