apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-workflows
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: simple-workflows
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
